# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build job-quest`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t job-quest`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

RUN addgroup --system job-quest && \
          adduser --system -G job-quest job-quest

COPY dist/job-quest job-quest
RUN chown -R job-quest:job-quest .

# You can remove this install step if you build with `--bundle` option.
# The bundled output will include external dependencies.
RUN npm --prefix job-quest --omit=dev -f install

CMD [ "node", "job-quest" ]
